blueprint:
  name: Single user lights
  description: When only one person is home, when light goes on, turn off all other lights (for defined lighs, e.g. bedrooms)
  domain: automation
  source_url: https://github.com/bruxy70/blueprints/single_user_lights.yaml
  input:
    light_list:
      name: Light list
      description: List of lights that will trigger all other lights off
      selector:
        target:
          entity:
            domain: light
trigger:
  - platform: state
    entity_id: !input light_list
    from: "off"
    to: "on"
condition:
  condition: template
  value_template: "{{ states.person | map(attribute='state') | select('eq','home') | list | length == 1 }}"
action:
  - service: light.turn_off
    data_template:
      entity_id: "{{ states.light | map(attribute='entity_id') | select('ne', trigger.entity_id) | join(', ') }}"
mode: single
